rules:
  no-color-literals:
    - 2
    -
      allow-rgba: true
  no-ids: 2
  class-name-format:
    - 2
    -
      allow-leading-underscore: true
      convention: hyphenatedbem
  variable-name-format:
    - 2
    -
      allow-leading-underscore: true
      convention: hyphenatedbem
  nesting-depth:
    - 2
    -
      max-depth: 5
  quotes:
    - 2
    -
      style: double
  no-vendor-prefixes: 0
  single-line-per-selector: 0
